//ACTIONS
export const GET_USER_VARIANT = 'GET_USER_VARIANT';
export const USER_VARIANT_FAILED = "USER_VARIANT_FAILED";
export const USER_VARIANT_SUCCEEDED = "USER_VARIANT_SUCCEEDED";
export const GET_PRICES = 'GET_PRICES';
export const GET_PRICES_FAILED = "GET_PRICES_FAILED";
export const GET_PRICES_SUCCEEDED = "GET_PRICES_SUCCEEDED";
export const SET_SELECTED_PRICE = 'SET_SELECTED_PRICE';
export const SET_NUMBER_OF_IBEACONS = 'SET_NUMBER_OF_IBEACONS';
export const APP_STATE_ACTIVE = "APP_STATE_ACTIVE"; 
export const APP_STATE_BACKGROUND = "APP_STATE_BACKGROUND";
